# Generated by Django 5.2.13 on 2026-04-14 20:15

import django.db.models.deletion
import notes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notelink_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=60, validators=[notes.models.validate_tag_name]),
        ),
        migrations.CreateModel(
            name='LLMInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('embedding', 'Embedding'), ('tagging', 'Tagging'), ('linking', 'Linking'), ('retrieval', 'Retrieval')], db_index=True, max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('input_hash', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_invocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
