# Generated by Django 5.2.13 on 2026-04-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_llminvocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='embedding_content_hash',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
